apiVersion: apps/v1
kind: Deployment
metadata:
  name: goecho-deployment
  labels:
    app: goecho-lb
spec:
  selector:
    matchLabels:
     project: goecho-label
  template:
    metadata:
      labels:
        project: goecho-label
    spec:
      containers:
        - name: container-goecho
          image: hargeon/goecho
          ports:
            - containerPort: 3000